version: "3.9"
services:
  postgres:
    image: postgres:17
    container_name: userlist_test_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: "no"

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userlist_test_app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: "no"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/16"

volumes:
  postgres_data:
